// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// scan_sequences
List scan_sequences(arma::mat Y_raw, arma::vec time_vec, arma::vec tau_grid, arma::vec epsilon_grid);
RcppExport SEXP _dyprop_scan_sequences(SEXP Y_rawSEXP, SEXP time_vecSEXP, SEXP tau_gridSEXP, SEXP epsilon_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y_raw(Y_rawSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time_vec(time_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau_grid(tau_gridSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type epsilon_grid(epsilon_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(scan_sequences(Y_raw, time_vec, tau_grid, epsilon_grid));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dyprop_scan_sequences", (DL_FUNC) &_dyprop_scan_sequences, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_dyprop(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
