# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_metrics <- function(X_clr, geneA_idx, geneB_idx, pseudotime, h_opt, lambda_reg = 1e-5) {
    .Call(`_dyprop_calc_metrics`, X_clr, geneA_idx, geneB_idx, pseudotime, h_opt, lambda_reg)
}

scan_sequences <- function(X_clr, time_vec, tau_grid, epsilon_grid, min_score = 0.5) {
    .Call(`_dyprop_scan_sequences`, X_clr, time_vec, tau_grid, epsilon_grid, min_score)
}

