# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scan_sequences <- function(Y_raw, time_vec, tau_grid, epsilon_grid) {
    .Call(`_dyprop_scan_sequences`, Y_raw, time_vec, tau_grid, epsilon_grid)
}

